services:
    sheer.find_by_date.listener:
        class: sheer\find_by_date\event\listener
        arguments:
            - '@dbal.conn'
            - '@template'
            - '@user'
            - '@request'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '@config'
            - '@auth'
        tags:
            - { name: event.listener }
